import HmppsAuditClient, { AuditEvent } from '../data/hmppsAuditClient'

export enum Page {
  EXAMPLE_PAGE = 'EXAMPLE_PAGE',
  INDEX_PAGE = 'INDEX_PAGE',
  APPOINTMENT_SHOW_PAGE = 'APPOINTMENT_SHOW_PAGE',
  SHOW_APPOINTMENT_ARRIVED_START_TIME_PAGE = 'SHOW_APPOINTMENT_ARRIVED_START_TIME_PAGE',
  SUBMIT_APPOINTMENT_ARRIVED_START_TIME_PAGE = 'SUBMIT_APPOINTMENT_ARRIVED_START_TIME_PAGE',
  SHOW_APPOINTMENT_ABSENT_START_TIME_PAGE = 'SHOW_APPOINTMENT_ABSENT_START_TIME_PAGE',
  SUBMIT_APPOINTMENT_ABSENT_START_TIME_PAGE = 'SUBMIT_APPOINTMENT_ABSENT_START_TIME_PAGE',
  SHOW_APPOINTMENT_ABLE_TO_WORK_PAGE = 'SHOW_APPOINTMENT_ABLE_TO_WORK_PAGE',
  SUBMIT_APPOINTMENT_ABLE_TO_WORK_PAGE = 'SUBMIT_APPOINTMENT_ABLE_TO_WORK_PAGE',
  SHOW_APPOINTMENT_UNABLE_TO_WORK_PAGE = 'SHOW_APPOINTMENT_UNABLE_TO_WORK_PAGE ',
  SUBMIT_APPOINTMENT_UNABLE_TO_WORK_PAGE = 'SUBMIT_APPOINTMENT_UNABLE_TO_WORK_PAGE ',
  SHOW_APPOINTMENT_COMPLETED_END_TIME_PAGE = 'SHOW_APPOINTMENT_COMPLETED_END_TIME_PAGE',
  SUBMIT_APPOINTMENT_COMPLETED_END_TIME_PAGE = 'SUBMIT_APPOINTMENT_COMPLETED_END_TIME_PAGE',
  SUBMIT_APPOINTMENT_LEFT_EARLY_END_TIME_PAGE = 'SUBMIT_APPOINTMENT_LEFT_EARLY_END_TIME_PAGE',
  SHOW_APPOINTMENT_LEFT_EARLY_END_TIME_PAGE = 'SHOW_APPOINTMENT_LEFT_EARLY_END_TIME_PAGE',
  SHOW_APPOINTMENT_COMPLETED_COMPLIANCE_PAGE = 'SHOW_APPOINTMENT_COMPLETED_COMPLIANCE_PAGE',
  SUBMIT_APPOINTMENT_COMPLETED_COMPLIANCE_PAGE = 'SUBMIT_APPOINTMENT_COMPLETED_COMPLIANCE_PAGE',
  SHOW_APPOINTMENT_LEFT_EARLY_COMPLIANCE_PAGE = 'SHOW_APPOINTMENT_LEFT_EARLY_COMPLIANCE_PAGE',
  SUBMIT_APPOINTMENT_LEFT_EARLY_COMPLIANCE_PAGE = 'SUBMIT_APPOINTMENT_LEFT_EARLY_COMPLIANCE_PAGE',
  SHOW_CONFIRM_WORKING_PAGE = 'SHOW_CONFIRM_WORKING_PAGE',
  SHOW_CONFIRM_UNABLE_TO_WORK_PAGE = 'SHOW_CONFIRM_UNABLE_TO_WORK_PAGE',
  SHOW_CONFIRM_ABSENT_PAGE = 'SHOW_CONFIRM_ABSENT_PAGE',
  SHOW_DEV_CLEAR_SESSION_STATUSES = 'SHOW_DEV_CLEAR_SESSION_STATUSES',
  SUBMIT_DEV_CLEAR_SESSION_STATUSES = 'SUBMIT_DEV_CLEAR_SESSION_STATUSES',
  SHOW_CONFIRM_COMPLETED_PAGE = 'SHOW_CONFIRM_COMPLETED_PAGE',
  SHOW_CONFIRM_LEFT_EARLY_PAGE = 'SHOW_CONFIRM_LEFT_EARLY_PAGE',
}

export interface PageViewEventDetails {
  who: string
  subjectId?: string
  subjectType?: string
  correlationId?: string
  details?: object
}

export default class AuditService {
  constructor(private readonly hmppsAuditClient: HmppsAuditClient) {}

  async logAuditEvent(event: AuditEvent) {
    await this.hmppsAuditClient.sendMessage(event)
  }

  async logPageView(page: Page, eventDetails: PageViewEventDetails) {
    const event: AuditEvent = {
      ...eventDetails,
      what: `PAGE_VIEW_${page}`,
    }
    await this.hmppsAuditClient.sendMessage(event)
  }
}
