import { AuditParams } from '../@types/user-defined'
import { AuditClient } from '../data'

export enum Page {
  EXAMPLE_PAGE = 'EXAMPLE_PAGE',
  VIEW_INDEX_PAGE = 'VIEW_INDEX_PAGE',
  VIEW_APPOINTMENT = 'VIEW_APPOINTMENT',
  VIEW_NEXT_SESSIONS = 'VIEW_NEXT_SESSIONS',
  VIEW_SESSION_APPOINTMENTS = 'VIEW_SESSION_APPOINTMENTS',
  VIEW_APPOINTMENT_ARRIVED_START_TIME = 'VIEW_APPOINTMENT_ARRIVED_START_TIME',
  EDIT_APPOINTMENT_ARRIVED_START_TIME = 'EDIT_APPOINTMENT_ARRIVED_START_TIME',
  VIEW_APPOINTMENT_ABSENT_START_TIME = 'VIEW_APPOINTMENT_ABSENT_START_TIME',
  EDIT_APPOINTMENT_ABSENT_START_TIME = 'EDIT_APPOINTMENT_ABSENT_START_TIME',
  VIEW_APPOINTMENT_ARRIVED_END_TIME = 'VIEW_APPOINTMENT_ARRIVED_END_TIME',
  EDIT_APPOINTMENT_ARRIVED_END_TIME = 'EDIT_APPOINTMENT_ARRIVED_END_TIME',
  VIEW_APPOINTMENT_COMPLETED_END_TIME = 'VIEW_APPOINTMENT_COMPLETED_END_TIME',
  EDIT_APPOINTMENT_COMPLETED_END_TIME = 'EDIT_APPOINTMENT_COMPLETED_END_TIME',
  VIEW_APPOINTMENT_COMPLETED_COMPLIANCE = 'VIEW_APPOINTMENT_COMPLETED_COMPLIANCE',
  EDIT_APPOINTMENT_COMPLETED_COMPLIANCE = 'EDIT_APPOINTMENT_COMPLETED_COMPLIANCE',
  VIEW_CONFIRM_ABSENT = 'VIEW_CONFIRM_ABSENT',
  VIEW_CONFIRM_COMPLETED = 'VIEW_CONFIRM_COMPLETED',
  VIEW_APPOINTMENT_LEFT_EARLY_REASON = 'VIEW_APPOINTMENT_LEFT_EARLY_REASON',
  CREATE_APPOINTMENT_LEFT_EARLY_REASON = 'CREATE_APPOINTMENT_LEFT_EARLY_REASON',
  VIEW_COOKIES_POLICY = 'VIEW_COOKIES_POLICY',
  VIEW_PRIVACY_NOTICE = 'VIEW_PRIVACY_NOTICE',
  VIEW_ACCESSIBILITY_STATEMENT = 'VIEW_ACCESSIBILITY_STATEMENT',
  VIEW_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE = 'VIEW_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE',
  EDIT_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE = 'EDIT_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE',
  VIEW_REVIEW_APPOINTMENT_ABSENT = 'VIEW_REVIEW_APPOINTMENT_ABSENT',
  VIEW_REVIEW_APPOINTMENT_COMPLETED = 'VIEW_REVIEW_APPOINTMENT_COMPLETED',
  VIEW_APPOINTMENT_NOTES_PAGE = 'VIEW_APPOINTMENT_NOTES_PAGE',
  CREATE_APPOINTMENT_ABSENT_PAGE = 'CREATE_ABSENT_APPOINTMENT_PAGE',
  CREATE_APPOINTMENT_COMPLETED_PAGE = 'CREATE_APPOINTMENT_COMPLETED_PAGE',
}

export default class AuditService {
  constructor(private readonly auditClient: AuditClient) {}

  async sendAuditMessage(auditParams: AuditParams) {
    await this.auditClient.sendAuditMessage(auditParams)
  }
}
